/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Automato;

/**
 *
 * @author Torres
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        chave = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        prev = new javax.swing.JRadioButton();
        faspm = new javax.swing.JRadioButton();
        chaveGet = new javax.swing.JTextField();
        passGet = new javax.swing.JPasswordField();
        dataIni = new javax.swing.JLabel();
        dataFim = new javax.swing.JLabel();
        dataIniGet = new javax.swing.JTextField();
        dataFimGet = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        loginPlanilha = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Extrator Contracheque");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chave.setText("Chave de Acesso:");
        Panel.add(chave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, 25));

        senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        senha.setText("Senha de Acesso:");
        Panel.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, 25));

        prev.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prev.setText("Previdência");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        Panel.add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        faspm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faspm.setText("FASPM");
        Panel.add(faspm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        Panel.add(chaveGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 75, -1));

        passGet.setText("password123");
        Panel.add(passGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 75, -1));

        dataIni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataIni.setText("Data Inicial:");
        Panel.add(dataIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 25));

        dataFim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataFim.setText("Data Final:");
        Panel.add(dataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 25));
        Panel.add(dataIniGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 105, -1));
        Panel.add(dataFimGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 105, -1));

        Start.setText("Start");
        Panel.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        loginPlanilha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginPlanilha.setText("Login por Planilha");
        Panel.add(loginPlanilha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Start;
    private javax.swing.JLabel chave;
    private javax.swing.JTextField chaveGet;
    private javax.swing.JLabel dataFim;
    private javax.swing.JTextField dataFimGet;
    private javax.swing.JLabel dataIni;
    private javax.swing.JTextField dataIniGet;
    private javax.swing.JRadioButton faspm;
    private javax.swing.JRadioButton loginPlanilha;
    private javax.swing.JPasswordField passGet;
    private javax.swing.JRadioButton prev;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables
}
